server:
  port: 5000

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: mxqq.mybatis.**.repo
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    database-id: mxqqdb


spring:
  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.212:5432/mxqqdb
    type: org.apache.ibatis.datasource.pooled.PooledDataSource
